"""add email to user

Revision ID: 717148035eba
Revises: 04885d0fe8e2
Create Date: 2025-11-11 22:36:06.115845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717148035eba'
down_revision = '04885d0fe8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
