"""create invoice table

Revision ID: fe1eddbe709d
Revises: 6766c891930a
Create Date: 2025-11-05 01:08:25.118970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1eddbe709d'
down_revision = '6766c891930a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.NUMERIC(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
